(* 
 * This is a driver file for the homework. 
 *
 * Do not edit this file -- instead, edit hw1.ml.
 *)
open Printf

let main () = 
  let silent = ref false in 
  let args = [
    "--silent", Arg.Set silent, "do not display a prompt or reminder"
  ] in 
  Arg.parse args (fun _ -> ()) "" ; 

  if not !silent then begin 
    flush stdout ; 
  end ; 
  let lexbuf = Lexing.from_channel stdin in
  let imp_command = Parse.com Lex.initial lexbuf in
  let env = Analyzer.empty_env in
  if not !silent then begin 
    Analyzer.check_c imp_command env ;
    printf "\n#include <iostream>\n#include <fstream>\n#include <string>\n    using namespace std;\n\n";
    print_string (Imp.find_include imp_command) ;
    printf "int main() {\n";
    print_string (Imp.com_to_str imp_command) ; 
    printf ";\nreturn 0;\n}"
  end ; 
(*  let sigma_0 = Hw1.empty_state in 
  let sigma_n =
    try
      Hw1.eval_com imp_command sigma_0
    with Failure msg -> printf "%s" :msg; sigma_0
  in
  ignore (sigma_n) ; 
  print_endline "" ; *)
  exit 0 
;;
main () ;;
