// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "address.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class PhoneDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Phone> {
} _Phone_default_instance_;
class ExamDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Exam> {
} _Exam_default_instance_;
class GradeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Grade> {
} _Grade_default_instance_;
class PersonDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Person> {
} _Person_default_instance_;
class Students_informationDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Students_information> {
} _Students_information_default_instance_;

namespace protobuf_address_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phone, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phone, number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phone, type_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Exam, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Exam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Exam, score_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Grade, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Grade, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Grade, course_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Grade, homework_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Grade, exams_),
  0,
  ~0u,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, age_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, phones_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, registed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Person, grades_),
  0,
  1,
  ~0u,
  ~0u,
  2,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Students_information, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Students_information, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Students_information, person_),
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(Phone)},
  { 8, 13, sizeof(Exam)},
  { 14, 21, sizeof(Grade)},
  { 24, 34, sizeof(Person)},
  { 40, 45, sizeof(Students_information)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Phone_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Exam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Grade_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Person_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Students_information_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "address.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace

void TableStruct::Shutdown() {
  _Phone_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Exam_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Grade_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _Person_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _Students_information_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Phone_default_instance_.DefaultConstruct();
  _Exam_default_instance_.DefaultConstruct();
  _Grade_default_instance_.DefaultConstruct();
  _Person_default_instance_.DefaultConstruct();
  _Students_information_default_instance_.DefaultConstruct();
  _Grade_default_instance_.get_mutable()->exams_ = const_cast< ::Exam*>(
      ::Exam::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\raddress.proto\"%\n\005Phone\022\016\n\006number\030\001 \002(\005"
      "\022\014\n\004type\030\002 \001(\t\"\025\n\004Exam\022\r\n\005score\030\002 \001(\005\"\?\n"
      "\005Grade\022\016\n\006course\030\001 \002(\t\022\020\n\010homework\030\002 \003(\005"
      "\022\024\n\005exams\030\003 \001(\0132\005.Exam\"q\n\006Person\022\014\n\004name"
      "\030\001 \002(\t\022\013\n\003age\030\002 \001(\005\022\n\n\002id\030\003 \003(\005\022\026\n\006phone"
      "s\030\004 \003(\0132\006.Phone\022\020\n\010registed\030\005 \001(\010\022\026\n\006gra"
      "des\030\006 \003(\0132\006.Grade\"/\n\024Students_informatio"
      "n\022\027\n\006person\030\001 \003(\0132\007.Person"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 306);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "address.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_address_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Phone::kNumberFieldNumber;
const int Phone::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Phone::Phone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_address_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Phone)
}
Phone::Phone(const Phone& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type()) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  number_ = from.number_;
  // @@protoc_insertion_point(copy_constructor:Phone)
}

void Phone::SharedCtor() {
  _cached_size_ = 0;
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  number_ = 0;
}

Phone::~Phone() {
  // @@protoc_insertion_point(destructor:Phone)
  SharedDtor();
}

void Phone::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Phone::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Phone::descriptor() {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[0].descriptor;
}

const Phone& Phone::default_instance() {
  protobuf_address_2eproto::InitDefaults();
  return *internal_default_instance();
}

Phone* Phone::New(::google::protobuf::Arena* arena) const {
  Phone* n = new Phone;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Phone::Clear() {
// @@protoc_insertion_point(message_clear_start:Phone)
  if (has_type()) {
    GOOGLE_DCHECK(!type_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*type_.UnsafeRawStringPointer())->clear();
  }
  number_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Phone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Phone)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 number = 1;
      case 1: {
        if (tag == 8u) {
          set_has_number();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string type = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Phone.type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Phone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Phone)
  return false;
#undef DO_
}

void Phone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Phone)
  // required int32 number = 1;
  if (has_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->number(), output);
  }

  // optional string type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Phone.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Phone)
}

::google::protobuf::uint8* Phone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Phone)
  // required int32 number = 1;
  if (has_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->number(), target);
  }

  // optional string type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Phone.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Phone)
  return target;
}

size_t Phone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Phone)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required int32 number = 1;
  if (has_number()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->number());
  }
  // optional string type = 2;
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Phone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Phone)
  GOOGLE_DCHECK_NE(&from, this);
  const Phone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Phone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Phone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Phone)
    MergeFrom(*source);
  }
}

void Phone::MergeFrom(const Phone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Phone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_type()) {
      set_has_type();
      type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
    }
    if (from.has_number()) {
      set_number(from.number());
    }
  }
}

void Phone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Phone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Phone::CopyFrom(const Phone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Phone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Phone::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void Phone::Swap(Phone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Phone::InternalSwap(Phone* other) {
  type_.Swap(&other->type_);
  std::swap(number_, other->number_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Phone::GetMetadata() const {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Phone

// required int32 number = 1;
bool Phone::has_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Phone::set_has_number() {
  _has_bits_[0] |= 0x00000002u;
}
void Phone::clear_has_number() {
  _has_bits_[0] &= ~0x00000002u;
}
void Phone::clear_number() {
  number_ = 0;
  clear_has_number();
}
::google::protobuf::int32 Phone::number() const {
  // @@protoc_insertion_point(field_get:Phone.number)
  return number_;
}
void Phone::set_number(::google::protobuf::int32 value) {
  set_has_number();
  number_ = value;
  // @@protoc_insertion_point(field_set:Phone.number)
}

// optional string type = 2;
bool Phone::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Phone::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
void Phone::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void Phone::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
const ::std::string& Phone::type() const {
  // @@protoc_insertion_point(field_get:Phone.type)
  return type_.GetNoArena();
}
void Phone::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Phone.type)
}
#if LANG_CXX11
void Phone::set_type(::std::string&& value) {
  set_has_type();
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Phone.type)
}
#endif
void Phone::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Phone.type)
}
void Phone::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Phone.type)
}
::std::string* Phone::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:Phone.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Phone::release_type() {
  // @@protoc_insertion_point(field_release:Phone.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Phone::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:Phone.type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Exam::kScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Exam::Exam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_address_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Exam)
}
Exam::Exam(const Exam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  score_ = from.score_;
  // @@protoc_insertion_point(copy_constructor:Exam)
}

void Exam::SharedCtor() {
  _cached_size_ = 0;
  score_ = 0;
}

Exam::~Exam() {
  // @@protoc_insertion_point(destructor:Exam)
  SharedDtor();
}

void Exam::SharedDtor() {
}

void Exam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Exam::descriptor() {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[1].descriptor;
}

const Exam& Exam::default_instance() {
  protobuf_address_2eproto::InitDefaults();
  return *internal_default_instance();
}

Exam* Exam::New(::google::protobuf::Arena* arena) const {
  Exam* n = new Exam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Exam::Clear() {
// @@protoc_insertion_point(message_clear_start:Exam)
  score_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Exam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Exam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 score = 2;
      case 2: {
        if (tag == 16u) {
          set_has_score();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Exam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Exam)
  return false;
#undef DO_
}

void Exam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Exam)
  // optional int32 score = 2;
  if (has_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->score(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Exam)
}

::google::protobuf::uint8* Exam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Exam)
  // optional int32 score = 2;
  if (has_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->score(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Exam)
  return target;
}

size_t Exam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Exam)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional int32 score = 2;
  if (has_score()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->score());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Exam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Exam)
  GOOGLE_DCHECK_NE(&from, this);
  const Exam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Exam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Exam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Exam)
    MergeFrom(*source);
  }
}

void Exam::MergeFrom(const Exam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Exam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_score()) {
    set_score(from.score());
  }
}

void Exam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Exam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Exam::CopyFrom(const Exam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Exam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Exam::IsInitialized() const {
  return true;
}

void Exam::Swap(Exam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Exam::InternalSwap(Exam* other) {
  std::swap(score_, other->score_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Exam::GetMetadata() const {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Exam

// optional int32 score = 2;
bool Exam::has_score() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Exam::set_has_score() {
  _has_bits_[0] |= 0x00000001u;
}
void Exam::clear_has_score() {
  _has_bits_[0] &= ~0x00000001u;
}
void Exam::clear_score() {
  score_ = 0;
  clear_has_score();
}
::google::protobuf::int32 Exam::score() const {
  // @@protoc_insertion_point(field_get:Exam.score)
  return score_;
}
void Exam::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:Exam.score)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Grade::kCourseFieldNumber;
const int Grade::kHomeworkFieldNumber;
const int Grade::kExamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Grade::Grade()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_address_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Grade)
}
Grade::Grade(const Grade& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      homework_(from.homework_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  course_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_course()) {
    course_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.course_);
  }
  if (from.has_exams()) {
    exams_ = new ::Exam(*from.exams_);
  } else {
    exams_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Grade)
}

void Grade::SharedCtor() {
  _cached_size_ = 0;
  course_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  exams_ = NULL;
}

Grade::~Grade() {
  // @@protoc_insertion_point(destructor:Grade)
  SharedDtor();
}

void Grade::SharedDtor() {
  course_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete exams_;
  }
}

void Grade::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Grade::descriptor() {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[2].descriptor;
}

const Grade& Grade::default_instance() {
  protobuf_address_2eproto::InitDefaults();
  return *internal_default_instance();
}

Grade* Grade::New(::google::protobuf::Arena* arena) const {
  Grade* n = new Grade;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Grade::Clear() {
// @@protoc_insertion_point(message_clear_start:Grade)
  homework_.Clear();
  if (_has_bits_[0 / 32] & 3u) {
    if (has_course()) {
      GOOGLE_DCHECK(!course_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*course_.UnsafeRawStringPointer())->clear();
    }
    if (has_exams()) {
      GOOGLE_DCHECK(exams_ != NULL);
      exams_->::Exam::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Grade::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Grade)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string course = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_course()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->course().data(), this->course().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Grade.course");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 homework = 2;
      case 2: {
        if (tag == 16u) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16u, input, this->mutable_homework())));
        } else if (tag == 18u) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_homework())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Exam exams = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_exams()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Grade)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Grade)
  return false;
#undef DO_
}

void Grade::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Grade)
  // required string course = 1;
  if (has_course()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->course().data(), this->course().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Grade.course");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->course(), output);
  }

  // repeated int32 homework = 2;
  for (int i = 0; i < this->homework_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->homework(i), output);
  }

  // optional .Exam exams = 3;
  if (has_exams()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->exams_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Grade)
}

::google::protobuf::uint8* Grade::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Grade)
  // required string course = 1;
  if (has_course()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->course().data(), this->course().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Grade.course");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->course(), target);
  }

  // repeated int32 homework = 2;
  for (int i = 0; i < this->homework_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->homework(i), target);
  }

  // optional .Exam exams = 3;
  if (has_exams()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->exams_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Grade)
  return target;
}

size_t Grade::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Grade)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required string course = 1;
  if (has_course()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->course());
  }
  // repeated int32 homework = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->homework_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->homework_size());
    total_size += data_size;
  }

  // optional .Exam exams = 3;
  if (has_exams()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->exams_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Grade::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Grade)
  GOOGLE_DCHECK_NE(&from, this);
  const Grade* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Grade>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Grade)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Grade)
    MergeFrom(*source);
  }
}

void Grade::MergeFrom(const Grade& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Grade)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  homework_.MergeFrom(from.homework_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_course()) {
      set_has_course();
      course_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.course_);
    }
    if (from.has_exams()) {
      mutable_exams()->::Exam::MergeFrom(from.exams());
    }
  }
}

void Grade::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Grade)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Grade::CopyFrom(const Grade& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Grade)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Grade::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void Grade::Swap(Grade* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Grade::InternalSwap(Grade* other) {
  homework_.UnsafeArenaSwap(&other->homework_);
  course_.Swap(&other->course_);
  std::swap(exams_, other->exams_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Grade::GetMetadata() const {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Grade

// required string course = 1;
bool Grade::has_course() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Grade::set_has_course() {
  _has_bits_[0] |= 0x00000001u;
}
void Grade::clear_has_course() {
  _has_bits_[0] &= ~0x00000001u;
}
void Grade::clear_course() {
  course_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_course();
}
const ::std::string& Grade::course() const {
  // @@protoc_insertion_point(field_get:Grade.course)
  return course_.GetNoArena();
}
void Grade::set_course(const ::std::string& value) {
  set_has_course();
  course_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Grade.course)
}
#if LANG_CXX11
void Grade::set_course(::std::string&& value) {
  set_has_course();
  course_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Grade.course)
}
#endif
void Grade::set_course(const char* value) {
  set_has_course();
  course_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Grade.course)
}
void Grade::set_course(const char* value, size_t size) {
  set_has_course();
  course_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Grade.course)
}
::std::string* Grade::mutable_course() {
  set_has_course();
  // @@protoc_insertion_point(field_mutable:Grade.course)
  return course_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Grade::release_course() {
  // @@protoc_insertion_point(field_release:Grade.course)
  clear_has_course();
  return course_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Grade::set_allocated_course(::std::string* course) {
  if (course != NULL) {
    set_has_course();
  } else {
    clear_has_course();
  }
  course_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), course);
  // @@protoc_insertion_point(field_set_allocated:Grade.course)
}

// repeated int32 homework = 2;
int Grade::homework_size() const {
  return homework_.size();
}
void Grade::clear_homework() {
  homework_.Clear();
}
::google::protobuf::int32 Grade::homework(int index) const {
  // @@protoc_insertion_point(field_get:Grade.homework)
  return homework_.Get(index);
}
void Grade::set_homework(int index, ::google::protobuf::int32 value) {
  homework_.Set(index, value);
  // @@protoc_insertion_point(field_set:Grade.homework)
}
void Grade::add_homework(::google::protobuf::int32 value) {
  homework_.Add(value);
  // @@protoc_insertion_point(field_add:Grade.homework)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Grade::homework() const {
  // @@protoc_insertion_point(field_list:Grade.homework)
  return homework_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Grade::mutable_homework() {
  // @@protoc_insertion_point(field_mutable_list:Grade.homework)
  return &homework_;
}

// optional .Exam exams = 3;
bool Grade::has_exams() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Grade::set_has_exams() {
  _has_bits_[0] |= 0x00000002u;
}
void Grade::clear_has_exams() {
  _has_bits_[0] &= ~0x00000002u;
}
void Grade::clear_exams() {
  if (exams_ != NULL) exams_->::Exam::Clear();
  clear_has_exams();
}
const ::Exam& Grade::exams() const {
  // @@protoc_insertion_point(field_get:Grade.exams)
  return exams_ != NULL ? *exams_
                         : *::Exam::internal_default_instance();
}
::Exam* Grade::mutable_exams() {
  set_has_exams();
  if (exams_ == NULL) {
    exams_ = new ::Exam;
  }
  // @@protoc_insertion_point(field_mutable:Grade.exams)
  return exams_;
}
::Exam* Grade::release_exams() {
  // @@protoc_insertion_point(field_release:Grade.exams)
  clear_has_exams();
  ::Exam* temp = exams_;
  exams_ = NULL;
  return temp;
}
void Grade::set_allocated_exams(::Exam* exams) {
  delete exams_;
  exams_ = exams;
  if (exams) {
    set_has_exams();
  } else {
    clear_has_exams();
  }
  // @@protoc_insertion_point(field_set_allocated:Grade.exams)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Person::kNameFieldNumber;
const int Person::kAgeFieldNumber;
const int Person::kIdFieldNumber;
const int Person::kPhonesFieldNumber;
const int Person::kRegistedFieldNumber;
const int Person::kGradesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Person::Person()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_address_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Person)
}
Person::Person(const Person& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      id_(from.id_),
      phones_(from.phones_),
      grades_(from.grades_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&age_, &from.age_,
    reinterpret_cast<char*>(&registed_) -
    reinterpret_cast<char*>(&age_) + sizeof(registed_));
  // @@protoc_insertion_point(copy_constructor:Person)
}

void Person::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&age_, 0, reinterpret_cast<char*>(&registed_) -
    reinterpret_cast<char*>(&age_) + sizeof(registed_));
}

Person::~Person() {
  // @@protoc_insertion_point(destructor:Person)
  SharedDtor();
}

void Person::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Person::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Person::descriptor() {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[3].descriptor;
}

const Person& Person::default_instance() {
  protobuf_address_2eproto::InitDefaults();
  return *internal_default_instance();
}

Person* Person::New(::google::protobuf::Arena* arena) const {
  Person* n = new Person;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Person::Clear() {
// @@protoc_insertion_point(message_clear_start:Person)
  id_.Clear();
  phones_.Clear();
  grades_.Clear();
  if (has_name()) {
    GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*name_.UnsafeRawStringPointer())->clear();
  }
  if (_has_bits_[0 / 32] & 6u) {
    ::memset(&age_, 0, reinterpret_cast<char*>(&registed_) -
      reinterpret_cast<char*>(&age_) + sizeof(registed_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Person::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Person)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Person.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 age = 2;
      case 2: {
        if (tag == 16u) {
          set_has_age();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 id = 3;
      case 3: {
        if (tag == 24u) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24u, input, this->mutable_id())));
        } else if (tag == 26u) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_id())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .Phone phones = 4;
      case 4: {
        if (tag == 34u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_phones()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // optional bool registed = 5;
      case 5: {
        if (tag == 40u) {
          set_has_registed();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &registed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .Grade grades = 6;
      case 6: {
        if (tag == 50u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_grades()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Person)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Person)
  return false;
#undef DO_
}

void Person::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Person)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Person.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 age = 2;
  if (has_age()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  // repeated int32 id = 3;
  for (int i = 0; i < this->id_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->id(i), output);
  }

  // repeated .Phone phones = 4;
  for (unsigned int i = 0, n = this->phones_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->phones(i), output);
  }

  // optional bool registed = 5;
  if (has_registed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->registed(), output);
  }

  // repeated .Grade grades = 6;
  for (unsigned int i = 0, n = this->grades_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->grades(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Person)
}

::google::protobuf::uint8* Person::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Person)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Person.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 age = 2;
  if (has_age()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  // repeated int32 id = 3;
  for (int i = 0; i < this->id_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(3, this->id(i), target);
  }

  // repeated .Phone phones = 4;
  for (unsigned int i = 0, n = this->phones_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->phones(i), false, target);
  }

  // optional bool registed = 5;
  if (has_registed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->registed(), target);
  }

  // repeated .Grade grades = 6;
  for (unsigned int i = 0, n = this->grades_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, this->grades(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Person)
  return target;
}

size_t Person::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Person)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }
  // repeated int32 id = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->id_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->id_size());
    total_size += data_size;
  }

  // repeated .Phone phones = 4;
  {
    unsigned int count = this->phones_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->phones(i));
    }
  }

  // repeated .Grade grades = 6;
  {
    unsigned int count = this->grades_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->grades(i));
    }
  }

  if (_has_bits_[0 / 32] & 6u) {
    // optional int32 age = 2;
    if (has_age()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->age());
    }

    // optional bool registed = 5;
    if (has_registed()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Person::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Person)
  GOOGLE_DCHECK_NE(&from, this);
  const Person* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Person>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Person)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Person)
    MergeFrom(*source);
  }
}

void Person::MergeFrom(const Person& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Person)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.MergeFrom(from.id_);
  phones_.MergeFrom(from.phones_);
  grades_.MergeFrom(from.grades_);
  if (from._has_bits_[0 / 32] & 7u) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (from.has_age()) {
      set_age(from.age());
    }
    if (from.has_registed()) {
      set_registed(from.registed());
    }
  }
}

void Person::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Person)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Person::CopyFrom(const Person& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Person)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Person::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->phones())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->grades())) return false;
  return true;
}

void Person::Swap(Person* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Person::InternalSwap(Person* other) {
  id_.UnsafeArenaSwap(&other->id_);
  phones_.UnsafeArenaSwap(&other->phones_);
  grades_.UnsafeArenaSwap(&other->grades_);
  name_.Swap(&other->name_);
  std::swap(age_, other->age_);
  std::swap(registed_, other->registed_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Person::GetMetadata() const {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Person

// required string name = 1;
bool Person::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Person::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void Person::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void Person::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
const ::std::string& Person::name() const {
  // @@protoc_insertion_point(field_get:Person.name)
  return name_.GetNoArena();
}
void Person::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Person.name)
}
#if LANG_CXX11
void Person::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Person.name)
}
#endif
void Person::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Person.name)
}
void Person::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Person.name)
}
::std::string* Person::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Person.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Person::release_name() {
  // @@protoc_insertion_point(field_release:Person.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Person::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Person.name)
}

// optional int32 age = 2;
bool Person::has_age() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Person::set_has_age() {
  _has_bits_[0] |= 0x00000002u;
}
void Person::clear_has_age() {
  _has_bits_[0] &= ~0x00000002u;
}
void Person::clear_age() {
  age_ = 0;
  clear_has_age();
}
::google::protobuf::int32 Person::age() const {
  // @@protoc_insertion_point(field_get:Person.age)
  return age_;
}
void Person::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
  // @@protoc_insertion_point(field_set:Person.age)
}

// repeated int32 id = 3;
int Person::id_size() const {
  return id_.size();
}
void Person::clear_id() {
  id_.Clear();
}
::google::protobuf::int32 Person::id(int index) const {
  // @@protoc_insertion_point(field_get:Person.id)
  return id_.Get(index);
}
void Person::set_id(int index, ::google::protobuf::int32 value) {
  id_.Set(index, value);
  // @@protoc_insertion_point(field_set:Person.id)
}
void Person::add_id(::google::protobuf::int32 value) {
  id_.Add(value);
  // @@protoc_insertion_point(field_add:Person.id)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Person::id() const {
  // @@protoc_insertion_point(field_list:Person.id)
  return id_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Person::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:Person.id)
  return &id_;
}

// repeated .Phone phones = 4;
int Person::phones_size() const {
  return phones_.size();
}
void Person::clear_phones() {
  phones_.Clear();
}
const ::Phone& Person::phones(int index) const {
  // @@protoc_insertion_point(field_get:Person.phones)
  return phones_.Get(index);
}
::Phone* Person::mutable_phones(int index) {
  // @@protoc_insertion_point(field_mutable:Person.phones)
  return phones_.Mutable(index);
}
::Phone* Person::add_phones() {
  // @@protoc_insertion_point(field_add:Person.phones)
  return phones_.Add();
}
::google::protobuf::RepeatedPtrField< ::Phone >*
Person::mutable_phones() {
  // @@protoc_insertion_point(field_mutable_list:Person.phones)
  return &phones_;
}
const ::google::protobuf::RepeatedPtrField< ::Phone >&
Person::phones() const {
  // @@protoc_insertion_point(field_list:Person.phones)
  return phones_;
}

// optional bool registed = 5;
bool Person::has_registed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Person::set_has_registed() {
  _has_bits_[0] |= 0x00000004u;
}
void Person::clear_has_registed() {
  _has_bits_[0] &= ~0x00000004u;
}
void Person::clear_registed() {
  registed_ = false;
  clear_has_registed();
}
bool Person::registed() const {
  // @@protoc_insertion_point(field_get:Person.registed)
  return registed_;
}
void Person::set_registed(bool value) {
  set_has_registed();
  registed_ = value;
  // @@protoc_insertion_point(field_set:Person.registed)
}

// repeated .Grade grades = 6;
int Person::grades_size() const {
  return grades_.size();
}
void Person::clear_grades() {
  grades_.Clear();
}
const ::Grade& Person::grades(int index) const {
  // @@protoc_insertion_point(field_get:Person.grades)
  return grades_.Get(index);
}
::Grade* Person::mutable_grades(int index) {
  // @@protoc_insertion_point(field_mutable:Person.grades)
  return grades_.Mutable(index);
}
::Grade* Person::add_grades() {
  // @@protoc_insertion_point(field_add:Person.grades)
  return grades_.Add();
}
::google::protobuf::RepeatedPtrField< ::Grade >*
Person::mutable_grades() {
  // @@protoc_insertion_point(field_mutable_list:Person.grades)
  return &grades_;
}
const ::google::protobuf::RepeatedPtrField< ::Grade >&
Person::grades() const {
  // @@protoc_insertion_point(field_list:Person.grades)
  return grades_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Students_information::kPersonFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Students_information::Students_information()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_address_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Students_information)
}
Students_information::Students_information(const Students_information& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      person_(from.person_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Students_information)
}

void Students_information::SharedCtor() {
  _cached_size_ = 0;
}

Students_information::~Students_information() {
  // @@protoc_insertion_point(destructor:Students_information)
  SharedDtor();
}

void Students_information::SharedDtor() {
}

void Students_information::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Students_information::descriptor() {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[4].descriptor;
}

const Students_information& Students_information::default_instance() {
  protobuf_address_2eproto::InitDefaults();
  return *internal_default_instance();
}

Students_information* Students_information::New(::google::protobuf::Arena* arena) const {
  Students_information* n = new Students_information;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Students_information::Clear() {
// @@protoc_insertion_point(message_clear_start:Students_information)
  person_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Students_information::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Students_information)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Person person = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_person()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Students_information)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Students_information)
  return false;
#undef DO_
}

void Students_information::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Students_information)
  // repeated .Person person = 1;
  for (unsigned int i = 0, n = this->person_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->person(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Students_information)
}

::google::protobuf::uint8* Students_information::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Students_information)
  // repeated .Person person = 1;
  for (unsigned int i = 0, n = this->person_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->person(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Students_information)
  return target;
}

size_t Students_information::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Students_information)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .Person person = 1;
  {
    unsigned int count = this->person_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->person(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Students_information::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Students_information)
  GOOGLE_DCHECK_NE(&from, this);
  const Students_information* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Students_information>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Students_information)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Students_information)
    MergeFrom(*source);
  }
}

void Students_information::MergeFrom(const Students_information& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Students_information)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  person_.MergeFrom(from.person_);
}

void Students_information::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Students_information)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Students_information::CopyFrom(const Students_information& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Students_information)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Students_information::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->person())) return false;
  return true;
}

void Students_information::Swap(Students_information* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Students_information::InternalSwap(Students_information* other) {
  person_.UnsafeArenaSwap(&other->person_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Students_information::GetMetadata() const {
  protobuf_address_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_address_2eproto::file_level_metadata[4];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Students_information

// repeated .Person person = 1;
int Students_information::person_size() const {
  return person_.size();
}
void Students_information::clear_person() {
  person_.Clear();
}
const ::Person& Students_information::person(int index) const {
  // @@protoc_insertion_point(field_get:Students_information.person)
  return person_.Get(index);
}
::Person* Students_information::mutable_person(int index) {
  // @@protoc_insertion_point(field_mutable:Students_information.person)
  return person_.Mutable(index);
}
::Person* Students_information::add_person() {
  // @@protoc_insertion_point(field_add:Students_information.person)
  return person_.Add();
}
::google::protobuf::RepeatedPtrField< ::Person >*
Students_information::mutable_person() {
  // @@protoc_insertion_point(field_mutable_list:Students_information.person)
  return &person_;
}
const ::google::protobuf::RepeatedPtrField< ::Person >&
Students_information::person() const {
  // @@protoc_insertion_point(field_list:Students_information.person)
  return person_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
